[package]
name = "broker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.99"
axum = "0.8.4"
common = { path = "../common" }
env_logger = "0.11.8"
log = "0.4.27"
postcard = { version = "1.1.3", features = ["use-std"] }
tokio = { version = "1.47.1", features = ["full"] }
